In [20]:
import numpy as np
import warnings
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [22]:
df = pd.read_excel(r'C:\Users\BHAVESH\IMARTICUS PYTHON TUTORIALS\DATASETS\Titanic_Survival_Train.xls',delimiter=' *, *')

In [23]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [24]:
df_copy=pd.DataFrame.copy(df)

In [25]:
df_copy=df_copy.drop(['Name','SibSp','Ticket','Parch'], axis=1)

In [26]:
df_copy=df_copy.drop(['PassengerId'], axis=1)

In [27]:
df_copy

Survived  Pclass     Sex   Age     Fare Cabin Embarked
0           0       3    male  22.0   7.2500   NaN        S
1           1       1  female  38.0  71.2833   C85        C
2           1       3  female  26.0   7.9250   NaN        S
3           1       1  female  35.0  53.1000  C123        S
4           0       3    male  35.0   8.0500   NaN        S
..        ...     ...     ...   ...      ...   ...      ...
886         0       2    male  27.0  13.0000   NaN        S
887         1       1  female  19.0  30.0000   B42        S
888         0       3  female   NaN  23.4500   NaN        S
889         1       1    male  26.0  30.0000  C148        C
890         0       3    male  32.0   7.7500   NaN        Q

[891 rows x 7 columns]

In [28]:
print(df_copy.isnull().sum())
print(df_copy.dtypes)

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
Cabin       687
Embarked      2
dtype: int64
Survived      int64
Pclass        int64
Sex          object
Age         float64
Fare        float64
Cabin        object
Embarked     object
dtype: object


In [29]:
df_copy.shape

(891, 7)

In [30]:
df_copy=df_copy.drop(['Cabin'],axis=1)

In [31]:
df_copy

Survived  Pclass     Sex   Age     Fare Embarked
0           0       3    male  22.0   7.2500        S
1           1       1  female  38.0  71.2833        C
2           1       3  female  26.0   7.9250        S
3           1       1  female  35.0  53.1000        S
4           0       3    male  35.0   8.0500        S
..        ...     ...     ...   ...      ...      ...
886         0       2    male  27.0  13.0000        S
887         1       1  female  19.0  30.0000        S
888         0       3  female   NaN  23.4500        S
889         1       1    male  26.0  30.0000        C
890         0       3    male  32.0   7.7500        Q

[891 rows x 6 columns]

In [32]:
df_copy.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
Embarked      2
dtype: int64

In [33]:
for i in df_copy.columns:
    if df_copy[i].dtype=='object' or df_copy[i].dtype=='bool':
        df_copy[i].fillna(df_copy[i].mode()[0], inplace=True)
    elif df_copy[i].dtype=='int64' or df_copy[i].dtype=='float64':
        df_copy[i].fillna(df_copy[i].mean(), inplace=True)

In [34]:
df_copy.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
Embarked    0
dtype: int64

In [35]:
df_copy.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
Fare        float64
Embarked     object
dtype: object

In [36]:
df_copy=pd.get_dummies(df_copy)

"""
colname=[]

for i in df_copy.columns:
    if df_copy[i].dtype=='object'
    colname.append(i)
colname

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder
for x in colname:
    df_copy[x]=le.fit_transform(df_copy[x])

"""

In [37]:
df_copy.head()

Survived  Pclass   Age     Fare  Sex_female  Sex_male  Embarked_C  \
0         0       3  22.0   7.2500           0         1           0   
1         1       1  38.0  71.2833           1         0           1   
2         1       3  26.0   7.9250           1         0           0   
3         1       1  35.0  53.1000           1         0           0   
4         0       3  35.0   8.0500           0         1           0   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [49]:
Y=df_copy.values[:,0]
Y.shape

(891,)

In [52]:
X=df_copy.values[:,[1,2,3,4,5,6,7,8]]
X.shape

(891, 8)

In [53]:
Y=Y.astype(int)

In [64]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test= train_test_split(X,Y, test_size=0.2, random_state=10)

In [65]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression()

In [66]:
Y_pred = classifier.predict(X_test)

In [67]:
print(list(zip(Y_test,Y_pred)))

[(0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 1), (0, 0), (1, 1), (0, 0), (0, 1), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (0, 1), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (1, 0), (0, 0), (1, 1), (0, 0), (0, 0), (1, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 0),

In [68]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification Report : ")
print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy Score : ",acc)

[[101  16]
 [ 15  47]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       117
           1       0.75      0.76      0.75        62

    accuracy                           0.83       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.83      0.83      0.83       179

Accuracy Score :  0.8268156424581006


In [63]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [70]:
Y_pred_prob=classifier.predict_proba(X_test)
print(Y_pred_prob)

[[0.92768845 0.07231155]
 [0.89585545 0.10414455]
 [0.90992252 0.09007748]
 [0.10672154 0.89327846]
 [0.1113374  0.8886626 ]
 [0.89342288 0.10657712]
 [0.9076945  0.0923055 ]
 [0.85491808 0.14508192]
 [0.92219161 0.07780839]
 [0.90079765 0.09920235]
 [0.76595265 0.23404735]
 [0.06991008 0.93008992]
 [0.21074252 0.78925748]
 [0.5543183  0.4456817 ]
 [0.78409652 0.21590348]
 [0.78549267 0.21450733]
 [0.91898083 0.08101917]
 [0.74882333 0.25117667]
 [0.44839758 0.55160242]
 [0.8439709  0.1560291 ]
 [0.91829008 0.08170992]
 [0.68049249 0.31950751]
 [0.26860121 0.73139879]
 [0.90770484 0.09229516]
 [0.7687543  0.2312457 ]
 [0.89611253 0.10388747]
 [0.89593597 0.10406403]
 [0.3985657  0.6014343 ]
 [0.870506   0.129494  ]
 [0.06112511 0.93887489]
 [0.10830171 0.89169829]
 [0.78549267 0.21450733]
 [0.35645641 0.64354359]
 [0.93123307 0.06876693]
 [0.24441555 0.75558445]
 [0.91767165 0.08232835]
 [0.4420424  0.5579576 ]
 [0.54163226 0.45836774]
 [0.85270146 0.14729854]
 [0.92219662 0.07780338]


In [71]:
for a in np.arange(0.4,0.61,0.01):
    pred_mine = np.where(Y_pred_prob[:,1]>a,1,0)
    cfm=confusion_matrix(Y_test , pred_mine)
    totalerr=cfm[0,1]+cfm[1,0]
    
    print("Errors at Threshold ",a,": ",totalerr," , type 2 error : ",cfm[1,0]," ,type 1 error : ",cfm[0,1])

Errors at Threshold  0.4 :  33  , type 2 error :  11  ,type 1 error :  22
Errors at Threshold  0.41000000000000003 :  33  , type 2 error :  11  ,type 1 error :  22
Errors at Threshold  0.42000000000000004 :  33  , type 2 error :  11  ,type 1 error :  22
Errors at Threshold  0.43000000000000005 :  33  , type 2 error :  11  ,type 1 error :  22
Errors at Threshold  0.44000000000000006 :  32  , type 2 error :  11  ,type 1 error :  21
Errors at Threshold  0.45000000000000007 :  29  , type 2 error :  12  ,type 1 error :  17
Errors at Threshold  0.4600000000000001 :  28  , type 2 error :  12  ,type 1 error :  16
Errors at Threshold  0.4700000000000001 :  28  , type 2 error :  12  ,type 1 error :  16
Errors at Threshold  0.4800000000000001 :  29  , type 2 error :  13  ,type 1 error :  16
Errors at Threshold  0.4900000000000001 :  30  , type 2 error :  14  ,type 1 error :  16
Errors at Threshold  0.5000000000000001 :  31  , type 2 error :  15  ,type 1 error :  16
Errors at Threshold  0.51000000

In [77]:
Y_cl=[]
for i in Y_pred_prob[:,1]:
    if i>0.46 :
        Y_cl.append(1)
    else:
        Y_cl.append(0)


In [79]:
Y_cl

[0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1]

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test , Y_cl)
print(cfm)

print("Classification Report : ")
print(classification_report(Y_test , Y_cl))

acc=accuracy_score(Y_test , Y_cl)
print("Accuracy Score : ",acc)

[[101  16]
 [ 12  50]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.89      0.86      0.88       117
           1       0.76      0.81      0.78        62

    accuracy                           0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.85      0.84      0.84       179

Accuracy Score :  0.8435754189944135


In [87]:
df_new1=pd.DataFrame()

In [88]:
df_new1["Predicted SURVIVAL"]=Y_cl

In [89]:
df_new1["Actual Survival"]=Y_test

In [104]:
df_new1

Predicted SURVIVAL  Actual Survival
0                     0                0
1                     0                0
2                     0                0
3                     1                1
4                     1                1
..                  ...              ...
174                   0                0
175                   0                0
176                   0                0
177                   0                0
178                   1                0

[179 rows x 2 columns]

In [106]:
df_new1.to_excel("TITANIC_SURVIVED.xlsx",header=True,index=True)